title: Rak Supermarket
author:
  name: Axcora
  email: axcora@gmail.com
  whatsapp: 6285646104747
  phone: 62895339403223
  address: Ruko Pasar Wisata Juanda Q.05-07
  country: Sidoarjo - East Java - Indonesia
  map: https://goo.gl/maps/EpcU3m3ryPMihifx7
description: Kebutuhan rak toko, rak minimarket,meja kasir,mesin kasir,rak gudang,rak farmasi lab ,perlengkapan retail.

url: https://raksupermarket.github.io/

show_excerpts: false # set to true to show excerpts on the homepage

# dablogger date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
dablogger:
  date_format: "%b %-d, %Y"


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

home:
  img1: https://raksupermarket.github.io//img/rak%20supermarket%20WARRIOR.jpg
  imgtitle1: rak toko murah,rak supermarket murah,rak minimarket murah.
  imgurl1: rakmurah
  img2: https://raksupermarket.github.io/img/rak%20supermarket%20athena.jpg
  imgtitle2: rak toko minimalis,rak supermarket minimalis,rak minimarket minimalis.
  imgurl2: rakminimalis
  img3: https://raksupermarket.github.io//img/rak%20GUDANG%20supermarket%20TOKO%20MINIMARKET.jpg
  imgtitle3: 
  imgurl3: rakheavy
  img4: https://raksupermarket.github.io//img/meja%20kasir.jpg
  imgtitle4: meja kasir besi 
  imgurl4: mejakasir
  img5: https://raksupermarket.github.io//img/mesin%20kasir.jpg
  imgtitle5: Mesin kasir toko minimarket supermarket barcode point of sale lengkap
  imgurl5: mesinkasir
 

  cover2: https://images.unsplash.com/reserve/LJIZlzHgQ7WPSh5KVTCB_Typewriter.jpg?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8d2hpdGUlMjBwZW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60
  covertitle: dablogger jekyll
  coverdesc: Da blogger is a free and open source code jekyll package set for build modern blog using jekyll ruby on rails. 
  coverintro: Ini adalah sebuah kode sumber terbuka untuk para blogger dalam kebutuhan ngeblog dan kaya fitur SEO otomatis nya, dengan jekyll akan menjadikan kesempurnaan akan kecepatan situs kamu selain itu dengan markdown akan semakin mobile dalam bekerja menggunakan dablogger jekyll web app ini untuk kebutuhan ngeblog dan ngonten kamu.  
  coverintro2: Hei ini adalah sebuah generator static site modern sangat cepat dan tanpa database hanya bekerja dengan .md files saja untuk kebutuhan artikel blog post .
  covercontent: Saatnya kini beralih ke dablogger untuk solusi terbaik ngeblog kamu, tanpa perlu ribet installasi database, hanya bekerja dengan markdown file atau kamu bisa menggunakan https://forestry.io untuk bekerja sebagai cms kamu, semua makin mudah , cepat dan tentu auto SEO untuk blog post artikel kamu, bersama dablogger jekyll saat nya menjadi lebih baik.
 

# Build settings
theme: dablogger

plugins:
 - jekyll-feed
 - jekyll-seo-tag
